### ISSUE TITLE
Host fonts on proper CDN

### ISSUE THREAD

**Issue by calebjacob** [near/pagoda-ui#7]
Our UI library currently depends on two fonts that aren't part of Google Fonts (FK Grotesk and Mona Sans). Our library is currently linking to the files served by `dev.near.org` like so as a temporary workaround:

```css
@font-face {
  font-family: 'Mona Sans';
  src:
    url('https://dev.near.org/fonts/Mona-Sans.woff2') format('woff2 supports variations'),
    url('https://dev.near.org/fonts/Mona-Sans.woff2') format('woff2-variations');
  font-weight: 200 900;
  font-stretch: 75% 125%;
}
```

Ideally, we should host both fonts on a proper CDN at some point.
